-- MySQL Script generated by MySQL Workbench
-- Fri Jul  7 23:55:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BufeteAbogados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BufeteAbogados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BufeteAbogados` DEFAULT CHARACTER SET utf8 ;
USE `BufeteAbogados` ;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `abogado`
--

CREATE TABLE `abogado` (
  `rutAbogado` int(11) NOT NULL,
  `nombreAbogado` varchar(45) NOT NULL,
  `apellidoPatAbogado` varchar(45) NOT NULL,
  `apellidoMatAbogado` varchar(45) NOT NULL,
  `fechaContratacionAbogado` date NOT NULL,
  `ValorHoraAbogado` int(11) NOT NULL,
  `Especialidad_idEspecialidad` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `abogado`
--

INSERT INTO `abogado` (`rutAbogado`, `nombreAbogado`, `apellidoPatAbogado`, `apellidoMatAbogado`, `fechaContratacionAbogado`, `ValorHoraAbogado`, `Especialidad_idEspecialidad`) VALUES
(22222222, 'Camilo', 'Barahona', 'Contreras', '2017-05-01', 26000, 1);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `atencion`
--

CREATE TABLE `atencion` (
  `idatencion` int(11) NOT NULL,
  `FechaHoraAtencion` datetime(5) NOT NULL,
  `Estado_idEstado` int(11) NOT NULL,
  `Abogado_rutAbogado` int(11) NOT NULL,
  `Cliente_rutCliente` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `atencion`
--

INSERT INTO `atencion` (`idatencion`, `FechaHoraAtencion`, `Estado_idEstado`, `Abogado_rutAbogado`, `Cliente_rutCliente`) VALUES
(1, '2017-07-13 12:30:00.00000', 1, 22222222, 12345678),
(4, '2017-07-13 01:00:00.00000', 1, 22222222, 12345678),
(5, '2017-07-13 13:00:00.00000', 1, 22222222, 18467705);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `cliente`
--

CREATE TABLE `cliente` (
  `rutCliente` int(11) NOT NULL,
  `nombreCliente` varchar(45) NOT NULL,
  `apellidoPatCliente` varchar(45) NOT NULL,
  `apellidoMatCliente` varchar(45) NOT NULL,
  `direccionCliente` varchar(45) NOT NULL,
  `telefonoCliente` varchar(45) NOT NULL,
  `TipoPersona_idTipoPersona` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `cliente`
--

INSERT INTO `cliente` (`rutCliente`, `nombreCliente`, `apellidoPatCliente`, `apellidoMatCliente`, `direccionCliente`, `telefonoCliente`, `TipoPersona_idTipoPersona`) VALUES
(12345678, 'Ruben', 'Carrasco', 'Vidal', 'av antonio varas 666', '123456', 1),
(18467705, 'camilo', 'barahona', 'contreras', 'av antonio varas 666', '123456', 1);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `especialidad`
--

CREATE TABLE `especialidad` (
  `idEspecialidad` int(11) NOT NULL,
  `nombreEspecialidad` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `especialidad`
--

INSERT INTO `especialidad` (`idEspecialidad`, `nombreEspecialidad`) VALUES
(1, 'Civil'),
(2, 'Penal'),
(3, 'Procesal'),
(4, 'Publico'),
(5, 'Comercial'),
(6, 'Economico'),
(7, 'Tributario'),
(8, 'Laboral');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `estado`
--

CREATE TABLE `estado` (
  `idEstado` int(11) NOT NULL,
  `nombreEstado` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `estado`
--

INSERT INTO `estado` (`idEstado`, `nombreEstado`) VALUES
(1, 'Agendada'),
(2, 'Confirmada'),
(3, 'Anulada'),
(4, 'Perdida'),
(5, 'Realizada');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `perfil`
--

CREATE TABLE `perfil` (
  `idPerfil` int(11) NOT NULL,
  `nombrePerfil` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `perfil`
--

INSERT INTO `perfil` (`idPerfil`, `nombrePerfil`) VALUES
(1, 'Gerente'),
(2, 'Administrador'),
(3, 'Secretaria'),
(4, 'Cliente');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `tipopersona`
--

CREATE TABLE `tipopersona` (
  `idTipoPersona` int(11) NOT NULL,
  `nombreTipoPersona` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `tipopersona`
--

INSERT INTO `tipopersona` (`idTipoPersona`, `nombreTipoPersona`) VALUES
(1, 'Natural'),
(2, 'Juridica');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuario`
--

CREATE TABLE `usuario` (
  `idUsuario` int(11) NOT NULL,
  `user` varchar(45) NOT NULL,
  `clave` varchar(45) NOT NULL,
  `Perfil_idPerfil` int(11) NOT NULL,
  `Cliente_rutCliente` int(11) DEFAULT NULL,
  `Abogado_rutAbogado` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `usuario`
--

INSERT INTO `usuario` (`idUsuario`, `user`, `clave`, `Perfil_idPerfil`, `Cliente_rutCliente`, `Abogado_rutAbogado`) VALUES
(0, 'secretaria', '81dc9bdb52d04dc20036dbd8313ed055', 3, NULL, NULL),
(1, 'administrador', '81dc9bdb52d04dc20036dbd8313ed055', 2, NULL, 22222222),
(2, 'cliente', '81dc9bdb52d04dc20036dbd8313ed055', 4, 12345678, NULL),
(3, 'gerente', '81dc9bdb52d04dc20036dbd8313ed055', 1, NULL, NULL);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `abogado`
--
ALTER TABLE `abogado`
  ADD PRIMARY KEY (`rutAbogado`),
  ADD KEY `fk_Abogado_Especialidad1_idx` (`Especialidad_idEspecialidad`);

--
-- Indices de la tabla `atencion`
--
ALTER TABLE `atencion`
  ADD PRIMARY KEY (`idatencion`,`Abogado_rutAbogado`,`Cliente_rutCliente`),
  ADD KEY `fk_atencion_Estado1_idx` (`Estado_idEstado`),
  ADD KEY `fk_atencion_Abogado1_idx` (`Abogado_rutAbogado`),
  ADD KEY `fk_atencion_Cliente1_idx` (`Cliente_rutCliente`);

--
-- Indices de la tabla `cliente`
--
ALTER TABLE `cliente`
  ADD PRIMARY KEY (`rutCliente`),
  ADD KEY `fk_Cliente_TipoPersona1_idx` (`TipoPersona_idTipoPersona`);

--
-- Indices de la tabla `especialidad`
--
ALTER TABLE `especialidad`
  ADD PRIMARY KEY (`idEspecialidad`);

--
-- Indices de la tabla `estado`
--
ALTER TABLE `estado`
  ADD PRIMARY KEY (`idEstado`);

--
-- Indices de la tabla `perfil`
--
ALTER TABLE `perfil`
  ADD PRIMARY KEY (`idPerfil`);

--
-- Indices de la tabla `tipopersona`
--
ALTER TABLE `tipopersona`
  ADD PRIMARY KEY (`idTipoPersona`);

--
-- Indices de la tabla `usuario`
--
ALTER TABLE `usuario`
  ADD PRIMARY KEY (`idUsuario`),
  ADD KEY `fk_Usuario_Perfil_idx` (`Perfil_idPerfil`),
  ADD KEY `fk_Usuario_Cliente1_idx` (`Cliente_rutCliente`),
  ADD KEY `fk_Usuario_Abogado1_idx` (`Abogado_rutAbogado`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `atencion`
--
ALTER TABLE `atencion`
  MODIFY `idatencion` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
--
-- AUTO_INCREMENT de la tabla `especialidad`
--
ALTER TABLE `especialidad`
  MODIFY `idEspecialidad` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
--
-- AUTO_INCREMENT de la tabla `estado`
--
ALTER TABLE `estado`
  MODIFY `idEstado` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
--
-- AUTO_INCREMENT de la tabla `perfil`
--
ALTER TABLE `perfil`
  MODIFY `idPerfil` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT de la tabla `tipopersona`
--
ALTER TABLE `tipopersona`
  MODIFY `idTipoPersona` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
--
-- AUTO_INCREMENT de la tabla `usuario`
--
ALTER TABLE `usuario`
  MODIFY `idUsuario` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `abogado`
--
ALTER TABLE `abogado`
  ADD CONSTRAINT `fk_Abogado_Especialidad1` FOREIGN KEY (`Especialidad_idEspecialidad`) REFERENCES `especialidad` (`idEspecialidad`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Filtros para la tabla `atencion`
--
ALTER TABLE `atencion`
  ADD CONSTRAINT `fk_atencion_Abogado1` FOREIGN KEY (`Abogado_rutAbogado`) REFERENCES `abogado` (`rutAbogado`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_atencion_Cliente1` FOREIGN KEY (`Cliente_rutCliente`) REFERENCES `cliente` (`rutCliente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_atencion_Estado1` FOREIGN KEY (`Estado_idEstado`) REFERENCES `estado` (`idEstado`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Filtros para la tabla `cliente`
--
ALTER TABLE `cliente`
  ADD CONSTRAINT `fk_Cliente_TipoPersona1` FOREIGN KEY (`TipoPersona_idTipoPersona`) REFERENCES `tipopersona` (`idTipoPersona`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Filtros para la tabla `usuario`
--
ALTER TABLE `usuario`
  ADD CONSTRAINT `fk_Usuario_Abogado1` FOREIGN KEY (`Abogado_rutAbogado`) REFERENCES `abogado` (`rutAbogado`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_Usuario_Cliente1` FOREIGN KEY (`Cliente_rutCliente`) REFERENCES `cliente` (`rutCliente`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_Usuario_Perfil` FOREIGN KEY (`Perfil_idPerfil`) REFERENCES `perfil` (`idPerfil`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
